#!/usr/bin/env python3
from pathlib import Path
import sys

template = """# PAPER_STATE

## RESEARCH_OBJECT
REALITY:
ACADEMIC:
DATA_OBJECT:
NOT_EQUAL_TO:

## ACADEMIC_POSITION
PRIMARY_LITERATURE:
SUBSTANTIVE_ANCHOR:
THEORY_ANCHOR:
METHOD_ANCHOR:
STYLE_ANCHOR:
PAPER_ARCHETYPE:

## PAPER_THESIS
BIG_PROBLEM:
CORE_RQ:
PRIMARY_NOVELTY_DELTA:
BELIEF_BEFORE:
BELIEF_AFTER:
DECISION: KEEP / PIVOT / SPLIT / EXIT

## THEORY_AND_MEASUREMENT
THEORY_PROVENANCE:
CORE_CONSTRUCTS:
DATA_MEANING:
UNIT_OF_ANALYSIS:

## EVIDENCE
PRIMARY_EVIDENCE:
MAIN_THREATS:
TARGET_JOURNAL_FAMILY:

## STATE_CONTROL
FROZEN_DECISIONS:
OPEN_UNCERTAINTIES:
DEFERRED_RESULTS:
RESET_HISTORY:
"""
path = Path(sys.argv[1] if len(sys.argv) > 1 else "PAPER_STATE.md")
if path.exists():
    raise SystemExit(f"Refusing to overwrite existing state: {path}")
path.write_text(template, encoding="utf-8")
print(path)
